/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_ndk_operate_datatype_MainActivity */

#ifndef _Included_com_zhangjunling_ndk_operate_datatype_MainActivity
#define _Included_com_zhangjunling_ndk_operate_datatype_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_ndk_operate_datatype_MainActivity
 * Method:    getHelloworldStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhangjunling_ndk_1operate_1datatype_MainActivity_getHelloworldStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
