/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangjunling_ndk_environment_ndkbuild_MainActivity */

#ifndef _Included_com_zhangjunling_ndk_environment_ndkbuild_MainActivity
#define _Included_com_zhangjunling_ndk_environment_ndkbuild_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangjunling_ndk_environment_ndkbuild_MainActivity
 * Method:    getStrFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhangjunling_ndk_1environment_1ndkbuild_MainActivity_getStrFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
